# ----------------------------- identity ------------------------------------

variable "wedding_slug" {
  description = "DNS-safe identifier for the wedding. Prefixes every resource name and is emitted as the `wedding:<slug>` DO tag."
  type        = string

  validation {
    condition     = can(regex("^[a-z0-9]([a-z0-9-]{1,30}[a-z0-9])$", var.wedding_slug))
    error_message = "wedding_slug must be 3-32 chars, lowercase alphanumerics and hyphens, and must not start or end with a hyphen."
  }
}

variable "environment" {
  description = "Deployment environment. Emitted as the `env:<environment>` DO tag and folded into resource names."
  type        = string

  validation {
    condition     = contains(["development", "staging", "production"], var.environment)
    error_message = "environment must be one of: development, staging, production."
  }
}

variable "project_id" {
  description = "UUID of the DigitalOcean project the database cluster is filed under. Null leaves it in the account default project."
  type        = string
  default     = null
}

# ----------------------------- placement -----------------------------------

variable "region" {
  description = "DigitalOcean datacenter slug for the Managed Postgres cluster, e.g. \"blr1\"."
  type        = string
  default     = "blr1"
}

variable "spaces_region" {
  description = "Spaces region slug for the guest-media bucket. Spaces is not offered in every datacenter -- verify availability before changing."
  type        = string
  default     = "blr1"
}

variable "vpc_uuid" {
  description = "UUID of the VPC to place the Postgres cluster in. Null places it in the region's default VPC."
  type        = string
  default     = null
}

# ----------------------------- postgres ------------------------------------

variable "db_engine_version" {
  description = "Major Postgres version for the managed cluster."
  type        = string
  default     = "16"
}

variable "db_size" {
  description = "Managed Postgres node size slug. db-s-1vcpu-1gb is the smallest available."
  type        = string
  default     = "db-s-1vcpu-1gb"
}

variable "db_node_count" {
  description = "Number of nodes in the cluster. 1 = single node, no standby. 2 or 3 adds HA and multiplies cost."
  type        = number
  default     = 1

  validation {
    condition     = var.db_node_count >= 1 && var.db_node_count <= 3
    error_message = "db_node_count must be between 1 and 3."
  }
}

variable "db_storage_size_mib" {
  description = "Optional storage override in MiB, as a string. Null keeps the plan's included storage. Storage can be grown but never shrunk."
  type        = string
  default     = null
}

variable "database_name" {
  description = "Logical database created inside the cluster for the wedding app."
  type        = string
  default     = "wedding"

  validation {
    condition     = can(regex("^[a-z][a-z0-9_]{0,62}$", var.database_name))
    error_message = "database_name must start with a lowercase letter and contain only lowercase letters, digits and underscores."
  }
}

variable "database_user" {
  description = "Application role created inside the cluster. Its password is generated by DigitalOcean, never by Terraform."
  type        = string
  default     = "wedding_app"

  validation {
    condition     = can(regex("^[a-z][a-z0-9_]{0,62}$", var.database_user))
    error_message = "database_user must start with a lowercase letter and contain only lowercase letters, digits and underscores."
  }
}

variable "maintenance_window" {
  description = "Weekly maintenance slot for the cluster, in UTC. Pick a window that is not the night before the wedding."
  type = object({
    day  = string
    hour = string
  })
  default = {
    day  = "tuesday"
    hour = "20:00:00"
  }
}

variable "use_private_host_for_app" {
  description = "Build database_uri from the cluster's VPC-private hostname instead of the public one. Only enable when the consumer actually sits inside vpc_uuid; App Platform apps reach Managed Postgres over the public endpoint."
  type        = bool
  default     = false
}

# ----------------------------- firewall ------------------------------------

variable "enable_database_firewall" {
  description = "Manage a trusted-sources firewall on the cluster. When false the cluster is reachable from any source that has the password -- only acceptable for throwaway dev clusters."
  type        = bool
  default     = true
}

variable "allowed_app_ids" {
  description = "App Platform app UUIDs allowed to reach Postgres. Rendered as `type = \"app\"` firewall rules. Wire the wedding-app module's app_id in here."
  type        = list(string)
  default     = []
}

variable "allowed_ip_addresses" {
  description = "Extra IPv4 addresses or CIDRs allowed through the Postgres firewall, e.g. a bastion or the office egress IP used for manual migrations."
  type        = list(string)
  default     = []
}

variable "allowed_tags" {
  description = "DigitalOcean tag names whose tagged droplets are allowed through the Postgres firewall."
  type        = list(string)
  default     = []
}

# ----------------------------- spaces --------------------------------------

variable "bucket_name_override" {
  description = "Explicit bucket name. Null derives `<slug>-media-<environment>`. Spaces bucket names are globally unique across all DO customers, so an override is occasionally needed."
  type        = string
  default     = null

  validation {
    condition     = var.bucket_name_override == null || can(regex("^[a-z0-9][a-z0-9.-]{1,61}[a-z0-9]$", coalesce(var.bucket_name_override, "xx")))
    error_message = "bucket_name_override must be a valid S3/Spaces bucket name: 3-63 chars, lowercase alphanumerics, dots and hyphens."
  }
}

variable "bucket_force_destroy" {
  description = "Permit `terraform destroy` to delete a bucket that still contains guest photos and videos. Keep false for anything a couple still cares about."
  type        = bool
  default     = false
}

variable "bucket_versioning_enabled" {
  description = "Keep non-current object versions. Protects against an accidental overwrite of guest media at the cost of extra storage."
  type        = bool
  default     = true
}

variable "noncurrent_version_expiration_days" {
  description = "Delete non-current object versions after this many days. Only applied when bucket_versioning_enabled is true."
  type        = number
  default     = 30
}

variable "abort_incomplete_multipart_upload_days" {
  description = "Reap abandoned multipart uploads after this many days. Guest video uploads from flaky phone networks leave these behind and they are billed as storage."
  type        = number
  default     = 7
}

variable "cors_allowed_origins" {
  description = "Origins permitted to issue browser uploads/reads directly against the bucket. Must include every hostname the app is served from."
  type        = list(string)

  validation {
    condition     = length(var.cors_allowed_origins) > 0
    error_message = "cors_allowed_origins must not be empty; browser uploads fail without at least the app's own origin."
  }
}

variable "cors_allowed_methods" {
  description = "HTTP methods permitted by the bucket CORS policy."
  type        = list(string)
  default     = ["GET", "HEAD", "PUT", "POST"]
}

variable "cors_max_age_seconds" {
  description = "How long a browser may cache the CORS preflight response."
  type        = number
  default     = 3600
}

# ----------------------------- cdn -----------------------------------------

variable "cdn_ttl" {
  description = "Edge cache TTL in seconds for the Spaces CDN endpoint. Guest media is immutable once uploaded, so a long TTL is safe."
  type        = number
  default     = 86400
}

variable "cdn_custom_domain" {
  description = "Optional vanity hostname for the CDN, e.g. media.muskan-sourav.imigrate.com. Requires cdn_certificate_name to be set as well."
  type        = string
  default     = null
}

variable "cdn_certificate_name" {
  description = "Name of an existing DigitalOcean certificate covering cdn_custom_domain. Certificates are not managed by this module."
  type        = string
  default     = null
}

# ----------------------------- misc ----------------------------------------

variable "extra_tags" {
  description = "Additional DigitalOcean tags merged onto taggable resources (currently the database cluster)."
  type        = list(string)
  default     = []
}
